server:
  port: ${PORT:8080}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8080/}  # Valor por defecto si SERVER_URL no está configurado

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=pago;encrypt=true;trustServerCertificate=true}
    username: ${DATABASE_USERNAME:sa}          ## Cambiar por tu usuario
    password: ${DATABASE_PASSWORD:Marion12345!}          ## Cambiar por tu contraseña
    driver-class-name: ${DATABASE_DRIVER:com.microsoft.sqlserver.jdbc.SQLServerDriver}
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Puede ser 'create', 'update', 'validate' o 'none'
    show-sql: false  # Puede true o false, para ver las consultas SQL en consola

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8080/swagger-ui.html
