server:
  port: ${PORT}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: AngelArenas


  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true


springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8085/swagger-ui.html

logging:
  level:
    Vallegrande.edu.pe.AngelArenas: INFO
    org.hibernate.SQL: DEBUG
