# docker-compose -f docker-compose-be.yml up -d
# docker compose -f docker-compose-be.yml up --build -d
# docker-compose -f docker-compose-be.yml down

version: '3.8'

services:
  backend:
    # image: juan321/springboot-sqls (esto de aqui reemplazaria al buil para utilizar una imagen aparte subida en dockerhub si se quiere utilizar de esta forma )
    image: jazett/crud-springboot-local:latest  # el . en el build significa que va ejecutar y utilizar el docker file que este en la misma carpeta
    container_name: angel-arenas-backend-local
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
      - SERVER_URL=http://localhost:8080  #aqui colocarias la ip publica de tu instancia backend
      - DATABASE_URL=jdbc:sqlserver://sqlserver-db-local:1433;databaseName=usuarios_db;encrypt=false;trustServerCertificate=true #para conexion a otra instancia externa reemplazar sqkserver-db por la ip publica de la otra instancia
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=Angel12345!
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    networks: # Conecta este contenedor a la red
      - my-network

# ---------------------------------------------------------
# DECLARACIÓN GLOBAL DE LA RED (Debe ir pegado a la izquierda)
# ---------------------------------------------------------
# CONSUMIR UNA RED EXISTENTE CREADA POR OTRO COMPOSE
networks:
  my-network:
    external: true   # usa la red creada por el compose de la base de datos