#docker-compose -f docker-compose-sebastian/docker-compose-be.yml up -d --build
#docker-compose -f docker-compose-sebastian/docker-compose-be.yml down
services:
  backend:
    build: 
      context: .. # Sube un nivel desde 'docker-compose/' para llegar a la raíz 'sebastian/'
      dockerfile: dockerfile-sebastian/Dockerfile # Ahora busca dentro de la carpeta raíz
    container_name: api_peirano
    ports:
      - "8085:8085"
    environment:
      - TZ=America/Lima
      - SERVER_PORT=8085
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database:1433;databaseName=BodegaPeiranoDBF;encrypt=false;trustServerCertificate=true;hibernate.jdbc.time_zone=America/Lima
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bodega-network

networks:
  bodega-network:
    external: true